#! /usr/bin/env bash

WORKING_DIR=.
PLAYLIST_ID=$1
RECORDINGS_DIR=$2

yt-dlp "$PLAYLIST_ID" \
  --audio-format m4a \
  --download-archive "$WORKING_DIR/downloaded/$PLAYLIST_ID.txt" \
  -o "$WORKING_DIR/output/%(title)s.%(ext)s" \
  -x

ls "$WORKING_DIR"/output/*.m4a | xargs -I % mv % "$RECORDINGS_DIR"
