#! /usr/bin/env bash

WORKING_DIR=.
PLAYLIST_ID=$1
RECORDINGS_DIR=$2

if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp must be installed."
    exit 1
fi

yt-dlp "$PLAYLIST_ID" \
  --audio-format m4a \
  --download-archive "$WORKING_DIR/downloaded/$PLAYLIST_ID.txt" \
  -o "$WORKING_DIR/output/%(title)s.%(ext)s" \
  -x

for f in "$WORKING_DIR"/output/*.m4a; do
  echo "Moving $f to $RECORDINGS_DIR..."
  mv "$f" "$RECORDINGS_DIR"
done
